# Generated by Django 2.2.10 on 2020-02-26 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='data',
        ),
    ]
