# Generated by Django 2.2.10 on 2020-02-26 07:00

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_data_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
