# Generated by Django 2.2.10 on 2020-02-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryScheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(max_length=30)),
                ('endpoint', models.CharField(max_length=200)),
                ('target_table', models.CharField(max_length=50)),
            ],
        ),
    ]
