# Generated by Django 2.2.10 on 2020-02-26 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celery_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CeleryScheduler',
        ),
    ]
