# Generated by Django 2.2.10 on 2020-06-07 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facebook',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('campaign_id', models.IntegerField(default=1123)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('likes_count', models.IntegerField(default=0)),
                ('shares_count', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('campaign_id', models.IntegerField(default=1123)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('likes_count', models.IntegerField(default=0)),
                ('retweets_count', models.IntegerField(default=0)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
