# Generated by Django 2.2.10 on 2020-06-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stubapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebook',
            name='post_id',
        ),
        migrations.AddField(
            model_name='facebook',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='twitter',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
