# Generated by Django 2.2.10 on 2020-06-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stubapi', '0002_auto_20200607_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebook',
            name='image',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='twitter',
            name='image',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='twitter',
            name='title',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='facebook',
            name='title',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='twitter',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
